//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTracking.AppClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppAuthenticationRequest", Namespace="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
        "v01/AppAS")]
    [System.SerializableAttribute()]
    public partial class AppAuthenticationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationField;
        
        private string ApplicationVersionField;
        
        private string IPField;
        
        private string PWDField;
        
        private string SystemIDField;
        
        private string SystemLoginUserField;
        
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Application {
            get {
                return this.ApplicationField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationField, value) != true)) {
                    this.ApplicationField = value;
                    this.RaisePropertyChanged("Application");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ApplicationVersion {
            get {
                return this.ApplicationVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationVersionField, value) != true)) {
                    this.ApplicationVersionField = value;
                    this.RaisePropertyChanged("ApplicationVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string PWD {
            get {
                return this.PWDField;
            }
            set {
                if ((object.ReferenceEquals(this.PWDField, value) != true)) {
                    this.PWDField = value;
                    this.RaisePropertyChanged("PWD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string SystemID {
            get {
                return this.SystemIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemIDField, value) != true)) {
                    this.SystemIDField = value;
                    this.RaisePropertyChanged("SystemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string SystemLoginUser {
            get {
                return this.SystemLoginUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemLoginUserField, value) != true)) {
                    this.SystemLoginUserField = value;
                    this.RaisePropertyChanged("SystemLoginUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppAuthenticationResponse", Namespace="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
        "v01/AppAS")]
    [System.SerializableAttribute()]
    public partial class AppAuthenticationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductTracking.AppClient.AcknowledgementInfo AcknowledgementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNextManagerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductTracking.AppClient.AcknowledgementInfo Acknowledgement {
            get {
                return this.AcknowledgementField;
            }
            set {
                if ((object.ReferenceEquals(this.AcknowledgementField, value) != true)) {
                    this.AcknowledgementField = value;
                    this.RaisePropertyChanged("Acknowledgement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpID {
            get {
                return this.EmpIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpIDField, value) != true)) {
                    this.EmpIDField = value;
                    this.RaisePropertyChanged("EmpID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserNextManager {
            get {
                return this.UserNextManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNextManagerField, value) != true)) {
                    this.UserNextManagerField = value;
                    this.RaisePropertyChanged("UserNextManager");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgementInfo", Namespace="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
        "v01/AppAS")]
    [System.SerializableAttribute()]
    public partial class AcknowledgementInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmationCode {
            get {
                return this.ConfirmationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmationCodeField, value) != true)) {
                    this.ConfirmationCodeField = value;
                    this.RaisePropertyChanged("ConfirmationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
        "v01/AppAS", ConfigurationName="AppClient.IAppAS")]
    public interface IAppAS {
        
        [System.ServiceModel.OperationContractAttribute(Action="AuthenticateUser", ReplyAction="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
            "v01/AppAS/IAppAS/AuthenticateUserResponse")]
        ProductTracking.AppClient.AppAuthenticationResponse AuthenticateUser(ProductTracking.AppClient.AppAuthenticationRequest appAuthenticationrequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="AuthenticateUser", ReplyAction="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
            "v01/AppAS/IAppAS/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<ProductTracking.AppClient.AppAuthenticationResponse> AuthenticateUserAsync(ProductTracking.AppClient.AppAuthenticationRequest appAuthenticationrequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="TestResponse", ReplyAction="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
            "v01/AppAS/IAppAS/TestResponseResponse")]
        string TestResponse(string stringinput);
        
        [System.ServiceModel.OperationContractAttribute(Action="TestResponse", ReplyAction="http://services.excelra.com/wsdl/authenticationservice/authentication/AppService/" +
            "v01/AppAS/IAppAS/TestResponseResponse")]
        System.Threading.Tasks.Task<string> TestResponseAsync(string stringinput);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppASChannel : ProductTracking.AppClient.IAppAS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppASClient : System.ServiceModel.ClientBase<ProductTracking.AppClient.IAppAS>, ProductTracking.AppClient.IAppAS {
        
        public AppASClient() {
        }
        
        public AppASClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppASClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppASClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppASClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProductTracking.AppClient.AppAuthenticationResponse AuthenticateUser(ProductTracking.AppClient.AppAuthenticationRequest appAuthenticationrequest) {
            return base.Channel.AuthenticateUser(appAuthenticationrequest);
        }
        
        public System.Threading.Tasks.Task<ProductTracking.AppClient.AppAuthenticationResponse> AuthenticateUserAsync(ProductTracking.AppClient.AppAuthenticationRequest appAuthenticationrequest) {
            return base.Channel.AuthenticateUserAsync(appAuthenticationrequest);
        }
        
        public string TestResponse(string stringinput) {
            return base.Channel.TestResponse(stringinput);
        }
        
        public System.Threading.Tasks.Task<string> TestResponseAsync(string stringinput) {
            return base.Channel.TestResponseAsync(stringinput);
        }
    }
}
