//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_CADViewXService
{
    using System;

    //public partial class ReactionsEntities : DbContext
    //{
    //    public ReactionsEntities()
    //        : base("name=ReactionsEntities")
    //    {
    //    }

    //    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    //    {
    //        throw new UnintentionalCodeFirstException();
    //    }

    ////public virtual DbSet<ShippmentUploadStatu> ShippmentUploadStatus { get; set; }
    ////public virtual DbSet<TanChemical> TanChemicals { get; set; }
    ////public virtual DbSet<Tan> Tans { get; set; }
    //}
}
