//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_CADViewXService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tan()
        {
            this.TanChemicals = new HashSet<TanChemical>();
        }
    
        //public int Id { get; set; }
        //public string tanNumber { get; set; }
        //public int TanCategory { get; set; }
        //public Nullable<int> TanState { get; set; }
        //public int BatchId { get; set; }
        //public System.DateTime DateCreated { get; set; }
        //public Nullable<int> WorkflowId { get; set; }
        //public Nullable<int> CurrentWorkflowUserRoleId { get; set; }
        //public string DocumentPath { get; set; }
        //public string LocalDocumentPath { get; set; }
        //public Nullable<System.DateTime> LastAccessedTime { get; set; }
        //public string DocumentReviwedUser { get; set; }
        //public bool IsQCCompleted { get; set; }
        //public int NumsCount { get; set; }
        //public int RxnCount { get; set; }
        //public string IsDuplicate { get; set; }
        //public string CAN { get; set; }
        //public string TanType { get; set; }
        //public string JournalName { get; set; }
        //public string Issue { get; set; }
        //public string JournalYear { get; set; }
        //public string TotalDocumentsPath { get; set; }
        //public string OCRStatus { get; set; }
        //public string LastAccessedBy_Id { get; set; }
        //public Nullable<System.DateTime> DocumentReadStartTime { get; set; }
        //public Nullable<System.DateTime> DocumentReadCompletedTime { get; set; }
        //public bool QCRequired { get; set; }
        //public int AllocatedType { get; set; }
        //public bool MarkedAsQuery { get; set; }
        //public Nullable<System.DateTime> TargetedDate { get; set; }
        //public int DocumentCurrentPage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TanChemical> TanChemicals { get; set; }
    }
}
