//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class RXNFILE {
    
    private string sOURCEField;
    
    private int fILENUMField;
    
    private int vERSIONField;
    
    private RXNFILEDOCUMENT[] dOCUMENTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString")]
    public string SOURCE {
        get {
            return this.sOURCEField;
        }
        set {
            this.sOURCEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int FILENUM {
        get {
            return this.fILENUMField;
        }
        set {
            this.fILENUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int VERSION {
        get {
            return this.vERSIONField;
        }
        set {
            this.vERSIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DOCUMENT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RXNFILEDOCUMENT[] DOCUMENT {
        get {
            return this.dOCUMENTField;
        }
        set {
            this.dOCUMENTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RXNFILEDOCUMENT {
    
    private string vIEWField;
    
    private string cANField;
    
    private string tANField;
    
    private string aNALYSTField;
    
    private string cOMMENTSField;
    
    private RXNFILEDOCUMENTRXN[] rXNGRPField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString")]
    public string VIEW {
        get {
            return this.vIEWField;
        }
        set {
            this.vIEWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString")]
    public string CAN {
        get {
            return this.cANField;
        }
        set {
            this.cANField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TAN {
        get {
            return this.tANField;
        }
        set {
            this.tANField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString")]
    public string ANALYST {
        get {
            return this.aNALYSTField;
        }
        set {
            this.aNALYSTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COMMENTS {
        get {
            return this.cOMMENTSField;
        }
        set {
            this.cOMMENTSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("RXN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public RXNFILEDOCUMENTRXN[] RXNGRP {
        get {
            return this.rXNGRPField;
        }
        set {
            this.rXNGRPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RXNFILEDOCUMENTRXN {
    
    private RXNFILEDOCUMENTRXNRXNID rXNIDField;
    
    private string rSDField;
    
    private RXNFILEDOCUMENTRXNNRN[] xREFGRPField;
    
    private RXNFILEDOCUMENTRXNSUBDEFN[] sUBDESCField;
    
    private RXNFILEDOCUMENTRXNRXNPROCESS rXNPROCESSField;
    
    private int noField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RXNFILEDOCUMENTRXNRXNID RXNID {
        get {
            return this.rXNIDField;
        }
        set {
            this.rXNIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString")]
    public string RSD {
        get {
            return this.rSDField;
        }
        set {
            this.rSDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("NRN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public RXNFILEDOCUMENTRXNNRN[] XREFGRP {
        get {
            return this.xREFGRPField;
        }
        set {
            this.xREFGRPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("SUBDEFN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public RXNFILEDOCUMENTRXNSUBDEFN[] SUBDESC {
        get {
            return this.sUBDESCField;
        }
        set {
            this.sUBDESCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RXNFILEDOCUMENTRXNRXNPROCESS RXNPROCESS {
        get {
            return this.rXNPROCESSField;
        }
        set {
            this.rXNPROCESSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int NO {
        get {
            return this.noField;
        }
        set {
            this.noField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RXNFILEDOCUMENTRXNRXNID {
    
    private int rXNNUMField;
    
    private bool rXNNUMFieldSpecified;
    
    private int rXNSEQField;
    
    private bool rXNSEQFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int RXNNUM {
        get {
            return this.rXNNUMField;
        }
        set {
            this.rXNNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RXNNUMSpecified {
        get {
            return this.rXNNUMFieldSpecified;
        }
        set {
            this.rXNNUMFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int RXNSEQ {
        get {
            return this.rXNSEQField;
        }
        set {
            this.rXNSEQField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RXNSEQSpecified {
        get {
            return this.rXNSEQFieldSpecified;
        }
        set {
            this.rXNSEQFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RXNFILEDOCUMENTRXNNRN {
    
    private int nRNNUMField;
    
    private bool nRNNUMFieldSpecified;
    
    private string nRNREGField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int NRNNUM {
        get {
            return this.nRNNUMField;
        }
        set {
            this.nRNNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NRNNUMSpecified {
        get {
            return this.nRNNUMFieldSpecified;
        }
        set {
            this.nRNNUMFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
    public string NRNREG {
        get {
            return this.nRNREGField;
        }
        set {
            this.nRNREGField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RXNFILEDOCUMENTRXNSUBDEFN {
    
    private int nRNNUMField;
    
    private bool nRNNUMFieldSpecified;
    
    private string sUBLOCField;
    
    private string sUBNAMEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int NRNNUM {
        get {
            return this.nRNNUMField;
        }
        set {
            this.nRNNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NRNNUMSpecified {
        get {
            return this.nRNNUMFieldSpecified;
        }
        set {
            this.nRNNUMFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUBLOC {
        get {
            return this.sUBLOCField;
        }
        set {
            this.sUBLOCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUBNAME {
        get {
            return this.sUBNAMEField;
        }
        set {
            this.sUBNAMEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RXNFILEDOCUMENTRXNRXNPROCESS {
    
    private RXNFILEDOCUMENTRXNRXNPROCESSRSN[] rSNField;
    
    private RXNFILEDOCUMENTRXNRXNPROCESSSTAGESUBSTAGECOND[][][] sTAGEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RSN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RXNFILEDOCUMENTRXNRXNPROCESSRSN[] RSN {
        get {
            return this.rSNField;
        }
        set {
            this.rSNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("SUBSTAGE", typeof(RXNFILEDOCUMENTRXNRXNPROCESSSTAGESUBSTAGECOND[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("COND", typeof(RXNFILEDOCUMENTRXNRXNPROCESSSTAGESUBSTAGECOND), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
    public RXNFILEDOCUMENTRXNRXNPROCESSSTAGESUBSTAGECOND[][][] STAGE {
        get {
            return this.sTAGEField;
        }
        set {
            this.sTAGEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RXNFILEDOCUMENTRXNRXNPROCESSRSN {
    
    private RXNFILEDOCUMENTRXNRXNPROCESSRSNTYPE tYPEField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RXNFILEDOCUMENTRXNRXNPROCESSRSNTYPE TYPE {
        get {
            return this.tYPEField;
        }
        set {
            this.tYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="normalizedString")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum RXNFILEDOCUMENTRXNRXNPROCESSRSNTYPE {
    
    /// <remarks/>
    FREE,
    
    /// <remarks/>
    anaerobic,
    
    /// <remarks/>
    biotransformation,
    
    /// <remarks/>
    chemoselective,
    
    /// <remarks/>
    combinatorial,
    
    /// <remarks/>
    electrochemical,
    
    /// <remarks/>
    enzymic,
    
    /// <remarks/>
    explosion,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("failed reaction")]
    failedreaction,
    
    /// <remarks/>
    fermentation,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("gas phase")]
    gasphase,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("green chemistry")]
    greenchemistry,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("green chemistry-catalyst")]
    greenchemistrycatalyst,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("green chemistry-process simplification")]
    greenchemistryprocesssimplification,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("green chemistry-reagent")]
    greenchemistryreagent,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("green chemistry-renewable feedstock")]
    greenchemistryrenewablefeedstock,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("green chemistry-solvent")]
    greenchemistrysolvent,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("green chemistry-waste reduction")]
    greenchemistrywastereduction,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("high pressure")]
    highpressure,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("in the dark")]
    inthedark,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("low pressure")]
    lowpressure,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("microwave irradiation")]
    microwaveirradiation,
    
    /// <remarks/>
    photochemical,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("prophetic reaction")]
    propheticreaction,
    
    /// <remarks/>
    radiochemical,
    
    /// <remarks/>
    regioselective,
    
    /// <remarks/>
    safety,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("solid state")]
    solidstate,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("solid-supported catalyst")]
    solidsupportedcatalyst,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("solid-supported reaction")]
    solidsupportedreaction,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("solid-supported reagent")]
    solidsupportedreagent,
    
    /// <remarks/>
    stereoselective,
    
    /// <remarks/>
    thermal,
    
    /// <remarks/>
    ultrasound,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RXNFILEDOCUMENTRXNRXNPROCESSSTAGESUBSTAGECOND {
    
    private RXNFILEDOCUMENTRXNRXNPROCESSSTAGESUBSTAGECONDTYPE tYPEField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RXNFILEDOCUMENTRXNRXNPROCESSSTAGESUBSTAGECONDTYPE TYPE {
        get {
            return this.tYPEField;
        }
        set {
            this.tYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="normalizedString")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum RXNFILEDOCUMENTRXNRXNPROCESSSTAGESUBSTAGECONDTYPE {
    
    /// <remarks/>
    TP,
    
    /// <remarks/>
    TM,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    PH,
}
